### ISSUE TITLE
Background Location Access:

### ISSUE THREAD

**Issue by prady32** [flurry/flurry-android-sdk#18]
Hi Our Application has been rejected for Background location access by play store.
We currently use flurry SDK 12.9.0 in our application.
Does Flurry use Background location ? We have verified in our project and found no other sdk is using Background location. Can you please confirm from your end

Thanks,
Pradeep

**Comment by srenrd** [comment]
Mine got approved after removing the Flurry SDK. So my bet would be yes.

**Comment by srenrd** [comment]
I spotted a setting for the FlurryAgent.Builder() if you set withIncludeBackgroundSessionsInMetrics(false), your app will also get approved.

**Comment by poting-oath** [comment]
@prady32 @srenrd Thanks for the report! Does your app/service start Flurry from the background mode?

Flurry SDK uses location service only for the foreground mode. However at the initial time, it intends to initialize the location as well. Therefore, if your app starts at the background mode, this "bug" will cause this background location request.

Please confirm your cases, and we will release the fix as soon as possible. Thanks!

**Comment by prady32** [comment]
Thanks @srenrd for the reply

@poting-oath yes we track some events when our app runs on background.

Please provide the fix as early as possible.
Is there any quick fix we can do now till new version is released so that we meet the 29th March deadline by google ?
Thanks in advance.

**Comment by poting-oath** [comment]
@prady32 Does your app start at the background mode like a service? If the app soon goes into the foreground mode after initialized Flurry, then the "background location" issue should not happen.
Before we release a new build with the fix, probably you can make sure your app goes into the foreground soon after you initialize Flurry.
You can try withIncludeBackgroundSessionsInMetrics(false) Srenrd suggeted as well.

**Comment by poting-oath** [comment]
@prady32 Please also try FlurryAgent.setReportLocation(false) immediately after initializing Flurry. It's kind of race condition that cannot guarantee though.

**Comment by poting-oath** [comment]
@prady32 Flurry SDK 12.13.0 released with this fix. Please try to use this build. Thanks!
