### ISSUE TITLE
Inconsistent license reference

### ISSUE THREAD

**Issue by thisisatestuseraccount** [flurry/flurry-android-sdk#28]
Howdy,

Might I suggest using the URL `http://www.apache.org/licenses/LICENSE-2.0.txt` and the name `The Apache Software License, Version 2.0` when publishing to Maven?

Such a change would allow this repository to be grouped with Google's Android dependencies, which are often published with this license. Referencing the repository in the licensing URL might seem more stable but it means that programmatic licensing plugins (which have to abide by strict lawyer wording) will see your license as a distinct license, despite it being the same as every other piece of Apache Software License Version 2.0 licensed software.

**Comment by harman-vz** [comment]
Hi, thanks for reaching out with the suggestion! We will address your concern and update our license name/url to the requested one, please be on the lookout for the change in our next release.
