### ISSUE TITLE
Wrong Device Models are shown in Event logs

### ISSUE THREAD

**Issue by KarthikaReddy** [flurry/flurry-android-sdk#8]
I use Flurry SDK version 7.2.3. The device model info sent for most of the mobiles by the SDK are wrong.

If we are using HTC M10 mobile, Flurry Event logs shows device model as  Hero Tab M10.
Same issue is seen with many devices, if we use Samsung S8, it shows as Samsung S9
Huawei G6 is shown for an LG G6. We have checked Phone settings and there it shows Phone Device model name correctly.

**Comment by poting-oath** [comment]
@KarthikaReddy We have released newly designed 12.#.#. Do you still see this issue? Thanks!
