### ISSUE TITLE
Android flurryAgent build issue

### ISSUE THREAD

**Issue by ankushpatel18** [flurry/flurry-android-sdk#9]
While trying to initialize flurry agent in application class. I always face this issue:-

**StrictMode policy violation; ~duration=11 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=65543 violation=2
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1440)**

**Comment by poting-oath** [comment]
@ankushpatel18 We have released 12.#.# with the fix. Please verify! Thanks!
